# Generated by Django 3.1.7 on 2021-03-09 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_user',
            name='balance',
        ),
    ]
