# Generated by Django 3.1.7 on 2021-03-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_remove_data_user_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_user',
            name='balance',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
