# Generated by Django 3.1.7 on 2021-03-09 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_data_user_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data_user',
            old_name='bonus_roi',
            new_name='roi',
        ),
    ]
