# Generated by Django 3.1.7 on 2021-03-09 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jenis_Invest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Invest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_bank', models.CharField(blank=True, max_length=50, null=True)),
                ('nama_pemilik_rekening', models.CharField(blank=True, max_length=100, null=True)),
                ('no_rekening', models.CharField(blank=True, max_length=50, null=True)),
                ('nominal', models.FloatField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, default=None, null=True)),
                ('roi', models.FloatField(blank=True, default=0, null=True)),
                ('roi_count', models.FloatField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('jenis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transaction.jenis_invest')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_management.data_user')),
            ],
        ),
    ]
