# Generated by Django 3.1.7 on 2021-03-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invest',
            old_name='status',
            new_name='status_invest',
        ),
        migrations.AddField(
            model_name='invest',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='invest',
            name='is_balik_modal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invest',
            name='modal',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
