# Generated by Django 3.1.7 on 2021-03-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_auto_20210309_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='via_bank',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
