# Generated by Django 3.1.7 on 2021-03-09 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_auto_20210309_1224'),
        ('transaction', '0005_auto_20210309_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bonus_generasi',
            old_name='user',
            new_name='from_user',
        ),
        migrations.AddField(
            model_name='bonus_generasi',
            name='for_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='user_management.data_user'),
        ),
    ]
