# Generated by Django 3.1.7 on 2021-03-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_weekly_withdraw_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invest',
            name='next_payment',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
