# Generated by Django 3.1.7 on 2021-03-09 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0008_invest_next_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonus_roi',
            name='user',
        ),
        migrations.AddField(
            model_name='bonus_roi',
            name='invest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transaction.invest'),
        ),
    ]
